@startuml View Classes diagram

left to right direction
skinparam groupInheritance 2
skinparam nodesep 10
skinparam ranksep 20


abstract class Component<T> {
  # container: HTMLElement
  # setImage(element: HTMLImageElement, src: string, alt?: string): void
  + render(data?: Partial<T>): HTMLElement
}

'----Хедер-----'
interface IHeader {
  counter: number
}

class HeaderView extends Component {
  -cartButton: HTMLButtonElement
  -cartCounter: HTMLElement
  + set counter(value: number)
}

HeaderView --> IHeader

'-----Карточки------'
'---Базовый класс---'
interface ICardBase {
  title: string
  price: string
}

abstract class CardView<T extends ICardBase> extends Component {
  #titleElement: HTMLElement
  #priceElement: HTMLElement

  + set title(value: ICardBase["title"])
  + set price(value: ICardBase["price"])
  + render(data: Partial<T>): HTMLElement
}


interface ICardInfo extends ICardBase {
  category: string
  image: { url: string; alt?: string }
}

interface ICardCatalogue extends ICardInfo {
  // расширение для каталога
}

'-----Карточка для каталога---'

abstract class CardInfoView<T extends ICardInfo> extends CardView {
  #categoryElement: HTMLElement
  #imageElement: HTMLImageElement

  # set category(value: ICardInfo['category'])
  # set image(value: ICardInfo['image'])
}

class CardCatalogueView extends CardInfoView {
  -showPreviewElement: HTMLElement
}

'-----Карточка для превью---'

'type controlState = { text: string; disabled: boolean }'

interface ICardPreview extends ICardInfo {
  description: string
  orderButtonState: controlState
}

class CardPreviewView extends CardInfoView {
  -descriptionElement: HTMLElement
  -orderButton: HTMLButtonElement

  + set description(value: string)
  + set orderButtonState(value: controlState)
}

CardPreviewView --> ICardPreview

'---Карточка для корзины----'
interface ICardCart extends ICardBase {
  index: number
}

class CardCartView extends CardView {
  -indexElement: HTMLElement
  + set index(value: number)
}

CardCatalogueView --> ICardCatalogue
CardCartView --> ICardCart

'---Каталог ---'
interface IGallery {
  catalogue: HTMLElement[]
}

class GalleryView extends Component {
  -catalogueElement: HTMLElement
  + set catalogue(items: HTMLElement[])
}

GalleryView --> IGallery

'------Модалка---------'
interface IModal {
  content: HTMLElement
}

class ModalView extends Component {
  -closeButton: HTMLButtonElement
  -contentContainer: HTMLElement
  + set content(item: HTMLElement)
  + open(): void
  + close(): void
}

ModalView --> IModal

'---Корзина ---'
interface ICart {
  products: HTMLElement[]
  cartPrice: number
  isCanOrder: boolean
}

class CartView extends Component {
  -productsList: HTMLUListElement
  -orderButton: HTMLButtonElement
  -priceElement: HTMLElement
  + set products(items: HTMLElement[])
  + set cartPrice(value: number)
  + set isCanOrder(value: boolean)
}

CartView --> ICart

'-----Кнопки----'
interface ITogglerButtons {
  activeBtnName: string
}

class TogglerButtonsView extends Component {
  -readonly activeBtnClassName: string
  -buttons: HTMLButtonElement[]
  + set activeBtn(value: string)
}

TogglerButtonsView --> ITogglerButtons

'---Формы----'
interface IFormStatus {
  submitDisabled: boolean
  errors: string[]
}

abstract class FormView<T> extends Component {
  #submitBtn: HTMLButtonElement
  #errorsElement: HTMLElement
  abstract set formStatus(value: T)
}

class FormOrderView extends FormView {
  -paymentToggler: IComponent<ITogglerButtons>
  -addressInput: HTMLInputElement
  + set paymentTogglerSettings(value: ITogglerButtons)
  + set formStatus(value: IFormStatus)
}

class FormContactsView extends FormView {
  -emailInput: HTMLInputElement
  -phoneInput: HTMLInputElement
  + set formStatus(value: IFormStatus)
}

'----Заказ успешен--'
interface IOrderSuccess {
  total: number
}

class OrderSuccessView extends Component {
  -totalElement: HTMLElement
  -buttonElement: HTMLButtonElement
  + set total(value: number)
}

OrderSuccessView --> IOrderSuccess

'hide <<interface>>
'hide class circle
'hide interface circle
@enduml